language: c
compiler:
  - clang
  - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake libgtk-3-dev librsvg2-dev libcairo2-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make
